### PR TITLE
Update to egui 0.28

### PR DESCRIPTION
**Pull request by crumblingstatue**

### CODE REVIEW

**Comment by bircni** [comment]
@crumblingstatue In the examples there some fixes are missing

**Comment by crumblingstatue** [comment]
> @crumblingstatue In the examples there some fixes are missing

Sorry about that, it should be fixed now 😅

**Comment by Auvrae** [comment]
Bump to 0.28.1 please.

**Comment by crumblingstatue** [comment]
> Bump to 0.28.1 please.

Is there a reason why it needs to be `0.28.1`? According to semver, `0.28` is compatible with `0.28.1`

**Comment by Auvrae** [comment]
It fixes a flickering issue on tool tips.

**Comment by amPerl** [comment]
Thanks! 0.28 should indeed be compatible with 0.28.1, so I'll keep it like this.

**Pull request merged**
